### ISSUE TITLE
Please add me as a collaborator

### ISSUE THREAD

**Issue by nanego** [jbbarth/redmine_cmdb#3]
Hi
I would be very thankful if you could add me as a collaborator on this repo :)

**Comment by jbbarth** [comment]
Done! Have fun ;) It would be great if this repo stays CMDB-neutral (e.g. the model is not tied to a specific CMDB vendor, but you can provide example integration scripts of course).

Anyway, if you need to do vendor specific things, as I don't maintain it seriously... who am I to oppose ? I can give you help on that tho if needed, let me know.

**Comment by nanego** [comment]
Thanks. That will be fun!
